export default [
  {title: 'Potatoes', price:5 , description:'Good old potatoes, with some spices and salt.'},
  {title: 'Rabbit and taters', price:10, description: 'Well cooked rabbit (not ruined), in a spicy stew. Served with tater-tots.'},
  {title: 'Lembas bread', price:3, description: 'Delicious lembas bread. Will keep you fed for days.'},
  {title: 'Potatoes', price:5 , description:'Good old potatoes, with some spices and salt.'},
  {title: 'Rabbit and taters', price:10, description: 'Well cooked rabbit (not ruined), in a spicy stew. Served with tater-tots.'},
  {title: 'Lembas bread', price:3, description: 'Delicious lembas bread. Will keep you fed for days.'},
  {title: 'Potatoes', price:5 , description:'Good old potatoes, with some spices and salt.'},
  {title: 'Rabbit and taters', price:10, description: 'Well cooked rabbit (not ruined), in a spicy stew. Served with tater-tots.'},
  {title: 'Lembas bread', price:3, description: 'Delicious lembas bread. Will keep you fed for days.'},
  {title: 'Potatoes', price:5 , description:'Good old potatoes, with some spices and salt.'},
  {title: 'Rabbit and taters', price:10, description: 'Well cooked rabbit (not ruined), in a spicy stew. Served with tater-tots.'},
  {title: 'Lembas bread', price:3, description: 'Delicious lembas bread. Will keep you fed for days.'},
  {title: 'Potatoes', price:5 , description:'Good old potatoes, with some spices and salt.'},
  {title: 'Rabbit and taters', price:10, description: 'Well cooked rabbit (not ruined), in a spicy stew. Served with tater-tots.'},
  {title: 'Lembas bread', price:3, description: 'Delicious lembas bread. Will keep you fed for days.'},
  {title: 'Potatoes', price:5 , description:'Good old potatoes, with some spices and salt.'},
  {title: 'Rabbit and taters', price:10, description: 'Well cooked rabbit (not ruined), in a spicy stew. Served with tater-tots.'},
  {title: 'Lembas bread', price:3, description: 'Delicious lembas bread. Will keep you fed for days.'},
  {title: 'Potatoes', price:5 , description:'Good old potatoes, with some spices and salt.'},
  {title: 'Rabbit and taters', price:10, description: 'Well cooked rabbit (not ruined), in a spicy stew. Served with tater-tots.'},
  {title: 'Lembas bread', price:3, description: 'Delicious lembas bread. Will keep you fed for days.'},
]
